version: '3'
services:
  main:
    image: kihaadhuffaru/fastapi-nats
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    networks:
      - nats
    #volumes
      #- ./data:/app/data
    depends_on:
      - nats
    container_name: container-main

  nats:
    image: kihaadhuffaru/nats
    ports:
      - "4222:4222"
      - "8222:8222"
    container_name: container-nats
    networks:
      - nats
    #command: "-DV"
networks:
  nats:
    driver: bridge
